name: CI for RandomChat

# Trigger workflow on push/pull request to main branch and manually
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Checkout the branch from input or default
          ref: ${{ github.event.inputs.branch || github.ref }}

      # Step 2: Set up Java (match your Spring Boot version)
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven dependencies (optional, speeds up builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Spring Boot project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 5: (Optional) Run tests
      - name: Run tests
        run: mvn test

      # Step 6: (Optional) List the generated jar
      - name: List target directory
        run: ls -l target/
